# Generated by Django 4.2.1 on 2023-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_password_model_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_model',
            name='your_password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password_model',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
